---
name: Firmware

on:
  push:
    branches:
      - main
    tags:
      - '*'
    paths:
      - 'firmware/**'
      - '.github/workflows/firmware.yml'
  pull_request:
    paths:
      - 'firmware/**'
      - '.github/workflows/firmware.yml'
  workflow_dispatch:

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        include:
          - board: h4ptix/rp2040/lonely
            artifact: h4ptix_rp2040_lonely.u2f
          - board: h4ptix/rp2040/basic
            artifact: h4ptix_rp2040_basic.u2f
          - board: h4ptix/rp2040/display
            artifact: h4ptix_rp2040_display.u2f
    name: 'build ${{ matrix.board }} board'
    permissions:
      contents: read
      pull-requests: read
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Drop .west
        shell: bash
        run: rm -rf .west

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.11

      - name: Setup Zephyr project
        uses: zephyrproject-rtos/action-zephyr-setup@v1
        with:
          app-path: firmware
          toolchains: arm-zephyr-eabi

      - name: Build
        shell: bash
        run: |
          (cd firmware && west build --pristine always -b "${{ matrix.board }}" app)
          mkdir -p out &&  mv firmware/build/zephyr/zephyr.uf2 "out/${{ matrix.artifact }}"
          echo "Done: out/${{ matrix.artifact }}"

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: "firmware-${{ matrix.artifact }}"
          path: "out/${{ matrix.artifact }}"
          if-no-files-found: error

      - name: Publish ${{ matrix.artifact }}
        if: "startsWith(github.ref, 'refs/tags/')"
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: "${{ secrets.PUBLISH_TOKEN }}"
          draft: true
          file: "out/${{ matrix.artifact }}"
